version: "3.1"
services:
    redis:
        image: redis:latest

    front_end:
        image: color_this:1.0 
        ports:
            - 80:5000
        environment:
            - PORT=5000
            - DBURI=mongodb+srv://asedhain:CapGv2jFwsT4rs2O@images-ulhix.mongodb.net/test?retryWrites=true&w=majority
            - dbname=Color
            - collection=images 
            - list_name=processing

    worker:
        image: worker:1.0
        environment:
            - DBURI=mongodb+srv://asedhain:CapGv2jFwsT4rs2O@images-ulhix.mongodb.net/test?retryWrites=true&w=majority
            - dbname=Color
            - collection=images
            - list_name=processing
