
name: Continious Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#   Node_CI:
#     runs-on: ubuntu-latest
#     env:
#       working-directory: ./app
#     strategy:
#       matrix:
#         node-version: [10.x, 12.x]
#     steps:
#     - uses: actions/checkout@v2
#     - working-directory: ${{ env.working-directory }}
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm install
#     - run: npm run build --if-present
#     - run: npm test
  
  Python_CI:
    runs-on: ubuntu-latest
    env:
      working-directory: ./worker
    strategy:
      matrix:
        python-version: [3.6, 3.8]
    steps:
      - uses: actions/checkout@v2
      - working-directory: ${{ env.working-directory }}
      - name: Use Python ${{ matrix.python-version }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt
      - run: python -m unittest
